// DO NOT EDIT
// This file has been auto-generated by hedwig-terraform-generator {{GENERATOR_VERSION}}

module "topic-my-topic" {
  source  = "standard-ai/hedwig-topic/google"
  version = "~> {{TFGoogleTopicModuleVersion}}"

  topic = "my-topic"

  enable_firehose_all_messages = "${var.enable_firehose_all_messages}"
}

module "topic-my-topic-2" {
  source  = "standard-ai/hedwig-topic/google"
  version = "~> {{TFGoogleTopicModuleVersion}}"

  topic = "my-topic2"

  enable_firehose_all_messages = "${var.enable_firehose_all_messages}"
}
