// DO NOT EDIT
// This file has been auto-generated by hedwig-terraform-generator {{GENERATOR_VERSION}}

variable "enable_firehose_all_topics" {
  default = false
  type    = bool
}

variable "enable_alerts" {
  default = false
  type    = bool
}
