// DO NOT EDIT
// This file has been auto-generated by hedwig-terraform-generator {{GENERATOR_VERSION}}

module "consumer-dev-myapp" {
  source  = "cloudchacho/hedwig-queue/google"
  version = "~> {{TFGoogleQueueModuleVersion}}"

  queue = "dev-myapp"

  iam_service_account = "myapp@project.iam.gserviceaccount.com"

  labels = {
    app = "myapp"
    env = "dev"
  }
}

module "consumer-dev-secondapp" {
  source  = "cloudchacho/hedwig-queue/google"
  version = "~> {{TFGoogleQueueModuleVersion}}"

  queue = "dev-secondapp"

  iam_service_account = "secondapp@project.iam.gserviceaccount.com"

  labels = {
    app = "secondapp"
    env = "dev"
  }
}
