// DO NOT EDIT
// This file has been auto-generated by hedwig-terraform-generator {{GENERATOR_VERSION}}

module "sub-dev-myapp-my-topic" {
  source  = "standard-ai/hedwig-subscription/google"
  version = "~> {{TFGoogleSubscriptionModuleVersion}}"

  queue = "dev-myapp"
  topic = "${module.topic-my-topic.name}"

  dataflow_tmp_gcs_location  = "${var.dataflow_tmp_gcs_location}"
  dataflow_template_gcs_path = "${var.dataflow_template_gcs_path}"

  labels = {
    app = "myapp"
    env = "dev"
  }
}

module "sub-dev-myapp-my-topic-2" {
  source  = "standard-ai/hedwig-subscription/google"
  version = "~> {{TFGoogleSubscriptionModuleVersion}}"

  queue = "dev-myapp"
  topic = "${module.topic-my-topic-2.name}"

  dataflow_tmp_gcs_location  = "${var.dataflow_tmp_gcs_location}"
  dataflow_template_gcs_path = "${var.dataflow_template_gcs_path}"

  labels = {
    app = "myapp"
    env = "dev"
  }
}

module "sub-dev-secondapp-my-topic-2" {
  source  = "standard-ai/hedwig-subscription/google"
  version = "~> {{TFGoogleSubscriptionModuleVersion}}"

  queue = "dev-secondapp"
  topic = "${module.topic-my-topic-2.name}"

  dataflow_tmp_gcs_location  = "${var.dataflow_tmp_gcs_location}"
  dataflow_template_gcs_path = "${var.dataflow_template_gcs_path}"

  labels = {
    app = "secondapp"
    env = "dev"
  }
}
