// DO NOT EDIT
// This file has been auto-generated by hedwig-terraform-generator {{GENERATOR_VERSION}}

module "topic-my-topic" {
  source  = "standard-ai/hedwig-topic/google"
  version = "~> {{TFGoogleTopicModuleVersion}}"

  topic = "my-topic"
}

module "topic-my-topic-2" {
  source  = "standard-ai/hedwig-topic/google"
  version = "~> {{TFGoogleTopicModuleVersion}}"

  topic = "my-topic2"
}
